import './cookiesPolicy.css';

const CookiesPolicy = () => {
  return (
    <div className='cu-container bg-gradient-4'>
      <h1 className='cu-title'>
        <p style={{ fontSize: '18px', marginTop: '5px' }}>
          Understanding how we use cookies on the SmashPay Platform
        </p>
      </h1>
      <div className='cu-items'>
        <h2 className='cu-subtitle'>I. Introduction</h2>
        <p className='cu-text'>
          This <b>Cookies Policy</b> (the “Policy”) governs the relations between you (“Client” or “you”) and
          any holding company, subsidiary, or entity belonging to the SmashPay group of companies (“SmashPay”,
          “we” or “us”), while you and SmashPay are hereinafter separately referred to as “Party” and jointly
          - as “Parties”, in regard to your use of the SmashPay Services and the use and application of
          cookies and similar technologies while using the SmashPay Platform.
        </p>
        <p className='cu-text'>
          You shall take your time and carefully read this Policy before using the SmashPay Services, so you
          are fully aware of your rights and obligations. In the spirit of transparency, this Policy provides
          detailed information about how and when we use cookies on the SmashPay Platform.
        </p>
        <p className='cu-text'>
          Unless stated otherwise, references shall be made to the SmashPay Terms of Service and the Privacy
          Policy (jointly the “SmashPay General Terms”), and all the defined terms, used in this Policy, shall
          have the same meaning as the one given to them in the SmashPay General Terms, as the case may be.
        </p>
        <p className='cu-text'>
          For the purposes of carrying out smooth electronic communication processes and technically
          error-free and optimized provision of the SmashPay Services, we store cookies on the grounds of your
          consent, for our legitimate interests and legitimate interests of third parties, as well as on other
          legal grounds under the relevant local legislation in every country of our operations. For the
          avoidance of doubt, this Policy does not apply to any digital services targeted at children.
        </p>
      </div>

      {/* Section II: Do We Use Cookies? */}
      <div className='cu-items'>
        <h2 className='cu-subtitle'>II. Do We Use Cookies?</h2>
        <p className='cu-text'>
          SmashPay and its partners, affiliates, analytics, and service providers use cookies and other
          similar technologies to ensure that everyone who uses the SmashPay Platform has the best possible
          user experience. When you visit the SmashPay Platform for the first time, a cookie banner will pop
          up and will give you an explanation about the cookies we use. As soon as you click on the “Accept
          All” button, you consent to us using all the categories of cookies, as described in this Policy. You
          can disable the use of cookies via your browser or via the given functionality at the Manage Cookies
          Button when you click on it, but please note that in the former case the SmashPay Platform may no
          longer work properly.
        </p>
      </div>

      {/* Section III: What Is a Cookie? */}
      <div className='cu-items'>
        <h2 className='cu-subtitle'>III. What Is a Cookie?</h2>
        <p className='cu-text'>
          A cookie is a small text file containing information generated by a websites server and placed on
          your personal computer or smart device. Cookies enable the website and your browser to interact in
          such a way that the website is able to present you with the most appropriate options and to
          customize services to your interests, based on your previous use of the website. Some of the cookies
          will only be used if you use certain features of our services or select certain preferences, and
          some cookies will always be used. You can find out more about each cookie we use by viewing our
          current Cookies List below and/or manage your preferences via the Manage Cookies button. We update
          this list regularly, so there may be additional cookies that are not yet listed.
        </p>
      </div>

      {/* Section IV: Cookies List */}
      <div className='cu-items'>
        <h2 className='cu-subtitle'>IV. Cookies List</h2>
        <p className='cu-text'>Depending on the purpose of each cookie, the cookies we use are:</p>
        <ol className='cu-list'>
          <li>
            <strong>Strictly Necessary Cookies:</strong> They are necessary for the SmashPay Platform to
            function properly and cannot be switched off in our system. They are usually only set in response
            to actions made by you which amount to a request for services, such as setting your privacy
            preferences, logging in, or filling in forms. You can set your browser to block or alert you about
            these cookies, but some parts of the SmashPay Platform will not then work properly. These cookies
            do not store any personally identifiable information.
          </li>
          <li>
            <strong>Functional Cookies:</strong> They enable the SmashPay Platform to provide enhanced
            functionality and personalization. They may be set by us or by third-party providers whose
            services we have added to the SmashPay Platform. If you do not allow these cookies, then some or
            all of these services may not function properly.
          </li>
          <li>
            <strong>Performance Cookies:</strong> They allow us to count visits and traffic sources so we can
            measure and improve the performance of the SmashPay Platform. They help us know which pages are
            the most and least popular and see how visitors move around the SmashPay Platform. All information
            these cookies collect is aggregated and therefore anonymous. If you do not allow these cookies, we
            will not know when you have visited the SmashPay Platform, and will not be able to monitor its
            performance.
          </li>
          <li>
            <strong>Targeting Cookies:</strong> These cookies may be set through the SmashPay Platform by our
            advertising partners. They may be used by those companies to build a profile of your interests and
            show you relevant adverts on other sites. They do not store directly personal information, but are
            based on uniquely identifying your browser and internet device. If you do not allow these cookies,
            you will experience less targeted advertising.
          </li>
          <li>
            <strong>Social Media Cookies:</strong> These cookies are set by a range of social media services
            that we have added to the SmashPay Platform to enable you to share our content with your friends
            and networks. They are capable of tracking your browser across other sites and building up a
            profile of your interests. This may impact the content and messages you see on other websites you
            visit. If you do not allow these cookies, you may not be able to use or see these sharing tools.
          </li>
          <li>
            <strong>Unknown Cookies:</strong> These cookies are used to better your customer journey on our
            site as well as collect information about your preferences and actions on the site. They do not
            collect personally identifiable data.
          </li>
        </ol>
        <p className='cu-text'>
          In relation to the controlling and processing of cookies, the cookies we use are:
        </p>
        <ol className='cu-list'>
          <li>
            <strong>First-party Cookies:</strong> These cookies are set by us.
          </li>
          <li>
            <strong>Third-party Cookies:</strong> These cookies are from a domain different from the domain of
            the SmashPay Platform you are visiting. These cookies are usually used to ease our advertising and
            marketing efforts.
          </li>
        </ol>
        <p className='cu-text'>Depending on the time the relevant cookie exists, the cookies we use are:</p>
        <ol className='cu-list'>
          <li>
            <strong>Session Cookies:</strong> They are temporary and expire once you close your browser.
          </li>
          <li>
            <strong>Persistent Cookies:</strong> They stay on your device for a fixed period of time or until
            you delete them. They help us recognize you as our current user, respectively Client, remember
            your preferences, and improve the SmashPay Platform functionality. In addition, the persistent
            cookies allow us to provide you with personalized advertisements and measure the effectiveness of
            the SmashPay Platform`s functionality and advertising.
          </li>
        </ol>
      </div>

      {/* Section V: Why Do We Use Cookies? */}
      <div className='cu-items'>
        <h2 className='cu-subtitle'>V. Why Do We Use Cookies?</h2>
        <p className='cu-text'>We use cookies for different purposes as listed below:</p>
        <ol className='cu-list'>
          <li>
            To recognize you when you sign in to use the SmashPay Services. This allows us to provide you with
            recommendations, display personalized content, and provide other customized features and services.
          </li>
          <li>
            To keep track of your specific preferences. This allows us to honor your likes and dislikes, such
            as your language and configuration preferences.
          </li>
          <li>
            To provide, develop, maintain, personalize, protect, and improve the SmashPay Platform, the
            SmashPay Services, and their content.
          </li>
          <li>
            To perform analytics, including to analyze and report on the use and performance of the SmashPay
            Services and any advertisements displayed on or delivered by or through them.
          </li>
          <li>To protect against, identify, and prevent fraud and other unlawful activity.</li>
          <li>
            To create aggregate data about the groups or categories of our users, respectively Clients
            (including advertising audiences), and for us, our partners, and third-party service providers to
            deliver, target, offer, market, or personalize advertising promotions and new industry-first
            features, relating to the SmashPay Services, as well as offerings to our Clients and partners
            (including limiting how often you see an advertisement).
          </li>
          <li>
            To report promotions and introduce new industry-first features, which allows us to measure and
            analyze the performance of the SmashPay Services.
          </li>
        </ol>
      </div>

      {/* Section VI: How Can You Manage Cookies? */}
      <div className='cu-items'>
        <h2 className='cu-subtitle'>VI. How Can You Manage Cookies?</h2>
        <p className='cu-text'>
          You can control the use of cookies when you first visit the SmashPay Platform via the options given
          to you on the Cookie Banner, at any time when you click on the Manage Cookies button above in the
          text of Section II, as well as at the individual browser level. If you choose not to activate any of
          the cookies categories or to later disable cookies, you may still visit the SmashPay Platform, but
          your ability to use some features of the SmashPay Services or areas of the SmashPay Platform may be
          limited.
        </p>
        <p className='cu-text'>
          You can generally activate or later deactivate the use of cookies through a functionality built into
          your web browser. The “Help” feature on most browsers will tell you how to prevent your browser from
          accepting new cookies, how to have the browser notify you when you receive a new cookie, how to
          block cookies, and when the relevant cookies will expire. If you block all cookies on your browser,
          neither we, nor third parties will transfer cookies to your browser. If you do this, however, you
          may have to manually adjust some preferences every time you visit the SmashPay Platform, and some of
          the SmashPay Platform, SmashPay Services, or features thereof may not work. To learn more about how
          to control cookies settings through your browser:
        </p>
        <ul className='cu-list'>
          <li>
            <strong>For Firefox “Private Browsing” managing cookies settings:</strong>{' '}
            <a href='https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop?redirectslug=enable-and-disable-cookies-website-preferences&redirectlocale=en-US'>
              Click here
            </a>
          </li>
          <li>
            <strong>For Chrome “Incognito” managing cookies settings:</strong>{' '}
            <a href='https://support.google.com/chrome/answer/95647?hl=en'>Click here</a>
          </li>
          <li>
            <strong>For Internet Explorer “InPrivate” managing cookies settings:</strong>{' '}
            <a href='https://support.microsoft.com/en-us/windows/delete-and-manage-cookies-168dab11-0753-043d-7c16-ede5947fc64d'>
              Click here
            </a>
          </li>
          <li>
            <strong>For Safari for Mac managing cookies settings:</strong>{' '}
            <a href='https://support.apple.com/en-gb/guide/safari/sfri11471/mac'>Click here</a>
          </li>
        </ul>
      </div>

      {/* Section VII: Miscellaneous */}
      <div className='cu-items'>
        <h2 className='cu-subtitle'>VII. Miscellaneous</h2>
        <ol className='cu-list'>
          <li>
            The content of this Policy is for your general information and use only. You acknowledge and agree
            that it may contain inaccuracies or errors, and we expressly exclude liability for any such
            inaccuracies or errors to the fullest extent permitted by law.
          </li>
          <li>
            SmashPay shall reserve its right to amend or supplement this Policy, including the above list of
            cookies, from time to time. Any such amendments or supplements shall become valid and in full
            force as of the date of their publishing on the SmashPay Platform unless otherwise indicated. You
            shall regularly check the SmashPay Platform to inform yourself about any such amendments or
            supplements, and your continued use of the SmashPay Platform constitutes your agreement to be
            bound by the latter.
          </li>
          <li>
            The descriptive headings in this Policy are inserted for convenience only and shall not affect the
            interpretation thereof.
          </li>
          <li>
            The failure by SmashPay to exercise any right or enforce any right or provision of this Policy
            shall not constitute a present or future waiver of such right or provision.
          </li>
          <li>
            None of your rights and obligations arising out of this Policy are assignable or transferable,
            without the prior written consent of SmashPay. SmashPay shall reserve the right to assign,
            delegate, or transfer the rights and obligations under this Policy to any third party at any time,
            without notice or your consent.
          </li>
          <li>
            This Policy is prepared and concluded in English language. In case the Policy or any part of it
            thereof is translated into another language for whatever reason, the English version shall
            prevail.
          </li>
          <li>
            If you have questions or concerns regarding this Policy or the SmashPay privacy practices, please
            contact us by email at <a href='mailto:support@smashpay.io'>support@smashpay.io</a>.
          </li>
        </ol>
      </div>
    </div>
  );
};

export default CookiesPolicy;
